### ISSUE TITLE
Searching tablet does not find appropriate item

### ISSUE THREAD

**Issue by lwskosa** [Pitan76/item-alchemy#39]
Example:

Scenario:
* ALL searched items were taught to tablet
* Player has enough EMC to afford items
----
* Searching for `steak` does not find item
* Searching for  `beef` finds both `Beef` and `Steak` items

Same pattern is present with other items, search is not very reliable

**Comment by OffsetMonkey538** [comment]
That seems to be because the mod checks if the id of an item contains the search text and because vanilla minecraft uses `minecraft:beef` for `Raw Beef` and `minecraft:cooked_beef` for `Steak`. This means that searching for `Steak` wont find the item as the identifier for `Steak` is `minecraft:cooked_beef`.

One way I can think of to solve this is to translate the name of the item and then check for a match with the search term. That way people could also search for items in their native language and it would still work.
