### ISSUE TITLE
Condenser does not work with Enchanted books

### ISSUE THREAD

**Issue by sobolewiok** [Pitan76/item-alchemy#85]
When i place a enchanted book with say protection 1 it makes blank enchanted books with no enchantment , they just glow and are called enchanted book but u cant apply it to the armour ,

**Comment by PTOM76** [comment]
Since it could disrupt the balance, we are making sure to remove items with NBT.
I will support you if you have any requests.

**Comment by BernardoGrigiastro** [comment]
I'm sorry but the "disrupt the balance" argument is kinda funny as disrupting the balance is exactly what project e and all its "family" do, not even the diminishing returns (or whatever it is called) config setting added when (or around) they finally stopped ignoring nbt, circa MC 1.15 iirc, helped!
IMHO adding nbt to project e was the best thing ever, it is wonderful being able to craft and enchant your perfect tool/weapon/armor, learn it and get a new one forever if anything happens. Its one of the very few mods that changed for the better instead of destroyed
So yeah this is my "vote" for adding nbt to item alchemy (along with all the other items ofc specially my beloved red katar :) )

P.S. A port of the ultimate un-balancer addon "Project EX" would also be superb ;)

**Comment by PTOM76** [comment]
I see, then I will try implementing it by switching enable/disable in Config.

**Comment by PTOM76** [comment]
Added Config.
The file is "config/itemalchemy/config.json"

default value of remove_data_from_copy_stack is true
if it is false, save nbt
